/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IPoolLiquidityInterface extends ethers.utils.Interface {
  functions: {
    "getLPTokenAddress()": FunctionFragment;
    "initPoolLiquidity(address,address,address,address,address,address,uint256,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getLPTokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initPoolLiquidity",
    values: [
      string,
      string,
      string,
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "getLPTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initPoolLiquidity",
    data: BytesLike
  ): Result;

  events: {};
}

export class IPoolLiquidity extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IPoolLiquidityInterface;

  functions: {
    getLPTokenAddress(overrides?: CallOverrides): Promise<[string]>;

    "getLPTokenAddress()"(overrides?: CallOverrides): Promise<[string]>;

    initPoolLiquidity(
      _accessControls: string,
      _token: string,
      _WETH: string,
      _factory: string,
      _owner: string,
      _wallet: string,
      _deadline: BigNumberish,
      _launchwindow: BigNumberish,
      _locktime: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initPoolLiquidity(address,address,address,address,address,address,uint256,uint256,uint256)"(
      _accessControls: string,
      _token: string,
      _WETH: string,
      _factory: string,
      _owner: string,
      _wallet: string,
      _deadline: BigNumberish,
      _launchwindow: BigNumberish,
      _locktime: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  getLPTokenAddress(overrides?: CallOverrides): Promise<string>;

  "getLPTokenAddress()"(overrides?: CallOverrides): Promise<string>;

  initPoolLiquidity(
    _accessControls: string,
    _token: string,
    _WETH: string,
    _factory: string,
    _owner: string,
    _wallet: string,
    _deadline: BigNumberish,
    _launchwindow: BigNumberish,
    _locktime: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initPoolLiquidity(address,address,address,address,address,address,uint256,uint256,uint256)"(
    _accessControls: string,
    _token: string,
    _WETH: string,
    _factory: string,
    _owner: string,
    _wallet: string,
    _deadline: BigNumberish,
    _launchwindow: BigNumberish,
    _locktime: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    getLPTokenAddress(overrides?: CallOverrides): Promise<string>;

    "getLPTokenAddress()"(overrides?: CallOverrides): Promise<string>;

    initPoolLiquidity(
      _accessControls: string,
      _token: string,
      _WETH: string,
      _factory: string,
      _owner: string,
      _wallet: string,
      _deadline: BigNumberish,
      _launchwindow: BigNumberish,
      _locktime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "initPoolLiquidity(address,address,address,address,address,address,uint256,uint256,uint256)"(
      _accessControls: string,
      _token: string,
      _WETH: string,
      _factory: string,
      _owner: string,
      _wallet: string,
      _deadline: BigNumberish,
      _launchwindow: BigNumberish,
      _locktime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getLPTokenAddress(overrides?: CallOverrides): Promise<BigNumber>;

    "getLPTokenAddress()"(overrides?: CallOverrides): Promise<BigNumber>;

    initPoolLiquidity(
      _accessControls: string,
      _token: string,
      _WETH: string,
      _factory: string,
      _owner: string,
      _wallet: string,
      _deadline: BigNumberish,
      _launchwindow: BigNumberish,
      _locktime: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initPoolLiquidity(address,address,address,address,address,address,uint256,uint256,uint256)"(
      _accessControls: string,
      _token: string,
      _WETH: string,
      _factory: string,
      _owner: string,
      _wallet: string,
      _deadline: BigNumberish,
      _launchwindow: BigNumberish,
      _locktime: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getLPTokenAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getLPTokenAddress()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initPoolLiquidity(
      _accessControls: string,
      _token: string,
      _WETH: string,
      _factory: string,
      _owner: string,
      _wallet: string,
      _deadline: BigNumberish,
      _launchwindow: BigNumberish,
      _locktime: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initPoolLiquidity(address,address,address,address,address,address,uint256,uint256,uint256)"(
      _accessControls: string,
      _token: string,
      _WETH: string,
      _factory: string,
      _owner: string,
      _wallet: string,
      _deadline: BigNumberish,
      _launchwindow: BigNumberish,
      _locktime: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
