/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TokenHelperInterface extends ethers.utils.Interface {
  functions: {
    "allowance(address,address,address)": FunctionFragment;
    "getTokenInfo(address)": FunctionFragment;
    "getTokensInfo(address[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "allowance",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenInfo",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokensInfo",
    values: [string[]]
  ): string;

  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokensInfo",
    data: BytesLike
  ): Result;

  events: {};
}

export class TokenHelper extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TokenHelperInterface;

  functions: {
    allowance(
      _token: string,
      _owner: string,
      _spender: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "allowance(address,address,address)"(
      _token: string,
      _owner: string,
      _spender: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTokenInfo(
      _address: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, BigNumber, string, string] & {
          addr: string;
          decimals: BigNumber;
          name: string;
          symbol: string;
        }
      ]
    >;

    "getTokenInfo(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, BigNumber, string, string] & {
          addr: string;
          decimals: BigNumber;
          name: string;
          symbol: string;
        }
      ]
    >;

    getTokensInfo(
      addresses: string[],
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, BigNumber, string, string] & {
          addr: string;
          decimals: BigNumber;
          name: string;
          symbol: string;
        })[]
      ]
    >;

    "getTokensInfo(address[])"(
      addresses: string[],
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, BigNumber, string, string] & {
          addr: string;
          decimals: BigNumber;
          name: string;
          symbol: string;
        })[]
      ]
    >;
  };

  allowance(
    _token: string,
    _owner: string,
    _spender: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "allowance(address,address,address)"(
    _token: string,
    _owner: string,
    _spender: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTokenInfo(
    _address: string,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, string, string] & {
      addr: string;
      decimals: BigNumber;
      name: string;
      symbol: string;
    }
  >;

  "getTokenInfo(address)"(
    _address: string,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, string, string] & {
      addr: string;
      decimals: BigNumber;
      name: string;
      symbol: string;
    }
  >;

  getTokensInfo(
    addresses: string[],
    overrides?: CallOverrides
  ): Promise<
    ([string, BigNumber, string, string] & {
      addr: string;
      decimals: BigNumber;
      name: string;
      symbol: string;
    })[]
  >;

  "getTokensInfo(address[])"(
    addresses: string[],
    overrides?: CallOverrides
  ): Promise<
    ([string, BigNumber, string, string] & {
      addr: string;
      decimals: BigNumber;
      name: string;
      symbol: string;
    })[]
  >;

  callStatic: {
    allowance(
      _token: string,
      _owner: string,
      _spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "allowance(address,address,address)"(
      _token: string,
      _owner: string,
      _spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokenInfo(
      _address: string,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string, string] & {
        addr: string;
        decimals: BigNumber;
        name: string;
        symbol: string;
      }
    >;

    "getTokenInfo(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string, string] & {
        addr: string;
        decimals: BigNumber;
        name: string;
        symbol: string;
      }
    >;

    getTokensInfo(
      addresses: string[],
      overrides?: CallOverrides
    ): Promise<
      ([string, BigNumber, string, string] & {
        addr: string;
        decimals: BigNumber;
        name: string;
        symbol: string;
      })[]
    >;

    "getTokensInfo(address[])"(
      addresses: string[],
      overrides?: CallOverrides
    ): Promise<
      ([string, BigNumber, string, string] & {
        addr: string;
        decimals: BigNumber;
        name: string;
        symbol: string;
      })[]
    >;
  };

  filters: {};

  estimateGas: {
    allowance(
      _token: string,
      _owner: string,
      _spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "allowance(address,address,address)"(
      _token: string,
      _owner: string,
      _spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokenInfo(
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTokenInfo(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokensInfo(
      addresses: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTokensInfo(address[])"(
      addresses: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    allowance(
      _token: string,
      _owner: string,
      _spender: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "allowance(address,address,address)"(
      _token: string,
      _owner: string,
      _spender: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTokenInfo(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTokenInfo(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTokensInfo(
      addresses: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTokensInfo(address[])"(
      addresses: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
