/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface PProxyStorageInterface extends ethers.utils.Interface {
  functions: {
    "addressToBytes32(address)": FunctionFragment;
    "bytes32ToAddress(bytes32)": FunctionFragment;
    "readAddress(bytes32)": FunctionFragment;
    "readBool(bytes32)": FunctionFragment;
    "storageRead(bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addressToBytes32",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "bytes32ToAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "readAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "readBool", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "storageRead",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addressToBytes32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bytes32ToAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "readAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "readBool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "storageRead",
    data: BytesLike
  ): Result;

  events: {};
}

export class PProxyStorage extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PProxyStorageInterface;

  functions: {
    addressToBytes32(
      _value: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "addressToBytes32(address)"(
      _value: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    bytes32ToAddress(
      _value: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "bytes32ToAddress(bytes32)"(
      _value: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    readAddress(_key: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    "readAddress(bytes32)"(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    readBool(_key: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

    "readBool(bytes32)"(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    storageRead(_key: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    "storageRead(bytes32)"(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  addressToBytes32(_value: string, overrides?: CallOverrides): Promise<string>;

  "addressToBytes32(address)"(
    _value: string,
    overrides?: CallOverrides
  ): Promise<string>;

  bytes32ToAddress(
    _value: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "bytes32ToAddress(bytes32)"(
    _value: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  readAddress(_key: BytesLike, overrides?: CallOverrides): Promise<string>;

  "readAddress(bytes32)"(
    _key: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  readBool(_key: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  "readBool(bytes32)"(
    _key: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  storageRead(_key: BytesLike, overrides?: CallOverrides): Promise<string>;

  "storageRead(bytes32)"(
    _key: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    addressToBytes32(
      _value: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "addressToBytes32(address)"(
      _value: string,
      overrides?: CallOverrides
    ): Promise<string>;

    bytes32ToAddress(
      _value: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "bytes32ToAddress(bytes32)"(
      _value: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    readAddress(_key: BytesLike, overrides?: CallOverrides): Promise<string>;

    "readAddress(bytes32)"(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    readBool(_key: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    "readBool(bytes32)"(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    storageRead(_key: BytesLike, overrides?: CallOverrides): Promise<string>;

    "storageRead(bytes32)"(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    addressToBytes32(
      _value: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "addressToBytes32(address)"(
      _value: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bytes32ToAddress(
      _value: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "bytes32ToAddress(bytes32)"(
      _value: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    readAddress(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "readAddress(bytes32)"(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    readBool(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "readBool(bytes32)"(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    storageRead(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "storageRead(bytes32)"(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addressToBytes32(
      _value: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "addressToBytes32(address)"(
      _value: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bytes32ToAddress(
      _value: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "bytes32ToAddress(bytes32)"(
      _value: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    readAddress(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "readAddress(bytes32)"(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    readBool(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "readBool(bytes32)"(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    storageRead(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "storageRead(bytes32)"(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
