/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IL2MigratorInterface extends ethers.utils.Interface {
  functions: {
    "finalizeMigrateDelegator((address,address,uint256,uint256,uint256,address))": FunctionFragment;
    "finalizeMigrateSender((address,address,uint256,uint256))": FunctionFragment;
    "finalizeMigrateUnbondingLocks((address,address,uint256,uint256[],address))": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "finalizeMigrateDelegator",
    values: [
      {
        l1Addr: string;
        l2Addr: string;
        stake: BigNumberish;
        delegatedStake: BigNumberish;
        fees: BigNumberish;
        delegate: string;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeMigrateSender",
    values: [
      {
        l1Addr: string;
        l2Addr: string;
        deposit: BigNumberish;
        reserve: BigNumberish;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeMigrateUnbondingLocks",
    values: [
      {
        l1Addr: string;
        l2Addr: string;
        total: BigNumberish;
        unbondingLockIds: BigNumberish[];
        delegate: string;
      }
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "finalizeMigrateDelegator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeMigrateSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeMigrateUnbondingLocks",
    data: BytesLike
  ): Result;

  events: {};
}

export class IL2Migrator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IL2MigratorInterface;

  functions: {
    finalizeMigrateDelegator(
      _params: {
        l1Addr: string;
        l2Addr: string;
        stake: BigNumberish;
        delegatedStake: BigNumberish;
        fees: BigNumberish;
        delegate: string;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    finalizeMigrateSender(
      _params: {
        l1Addr: string;
        l2Addr: string;
        deposit: BigNumberish;
        reserve: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    finalizeMigrateUnbondingLocks(
      _params: {
        l1Addr: string;
        l2Addr: string;
        total: BigNumberish;
        unbondingLockIds: BigNumberish[];
        delegate: string;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  finalizeMigrateDelegator(
    _params: {
      l1Addr: string;
      l2Addr: string;
      stake: BigNumberish;
      delegatedStake: BigNumberish;
      fees: BigNumberish;
      delegate: string;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  finalizeMigrateSender(
    _params: {
      l1Addr: string;
      l2Addr: string;
      deposit: BigNumberish;
      reserve: BigNumberish;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  finalizeMigrateUnbondingLocks(
    _params: {
      l1Addr: string;
      l2Addr: string;
      total: BigNumberish;
      unbondingLockIds: BigNumberish[];
      delegate: string;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    finalizeMigrateDelegator(
      _params: {
        l1Addr: string;
        l2Addr: string;
        stake: BigNumberish;
        delegatedStake: BigNumberish;
        fees: BigNumberish;
        delegate: string;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    finalizeMigrateSender(
      _params: {
        l1Addr: string;
        l2Addr: string;
        deposit: BigNumberish;
        reserve: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    finalizeMigrateUnbondingLocks(
      _params: {
        l1Addr: string;
        l2Addr: string;
        total: BigNumberish;
        unbondingLockIds: BigNumberish[];
        delegate: string;
      },
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    finalizeMigrateDelegator(
      _params: {
        l1Addr: string;
        l2Addr: string;
        stake: BigNumberish;
        delegatedStake: BigNumberish;
        fees: BigNumberish;
        delegate: string;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    finalizeMigrateSender(
      _params: {
        l1Addr: string;
        l2Addr: string;
        deposit: BigNumberish;
        reserve: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    finalizeMigrateUnbondingLocks(
      _params: {
        l1Addr: string;
        l2Addr: string;
        total: BigNumberish;
        unbondingLockIds: BigNumberish[];
        delegate: string;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    finalizeMigrateDelegator(
      _params: {
        l1Addr: string;
        l2Addr: string;
        stake: BigNumberish;
        delegatedStake: BigNumberish;
        fees: BigNumberish;
        delegate: string;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    finalizeMigrateSender(
      _params: {
        l1Addr: string;
        l2Addr: string;
        deposit: BigNumberish;
        reserve: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    finalizeMigrateUnbondingLocks(
      _params: {
        l1Addr: string;
        l2Addr: string;
        total: BigNumberish;
        unbondingLockIds: BigNumberish[];
        delegate: string;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
