/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface L1ArbitrumMessengerInterface extends ethers.utils.Interface {
  functions: {
    "inbox()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "inbox", values?: undefined): string;

  decodeFunctionResult(functionFragment: "inbox", data: BytesLike): Result;

  events: {
    "TxToL2(address,address,uint256,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "TxToL2"): EventFragment;
}

export type TxToL2Event = TypedEvent<
  [string, string, BigNumber, string] & {
    from: string;
    to: string;
    seqNum: BigNumber;
    data: string;
  }
>;

export class L1ArbitrumMessenger extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: L1ArbitrumMessengerInterface;

  functions: {
    inbox(overrides?: CallOverrides): Promise<[string]>;
  };

  inbox(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    inbox(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "TxToL2(address,address,uint256,bytes)"(
      from?: string | null,
      to?: string | null,
      seqNum?: BigNumberish | null,
      data?: null
    ): TypedEventFilter<
      [string, string, BigNumber, string],
      { from: string; to: string; seqNum: BigNumber; data: string }
    >;

    TxToL2(
      from?: string | null,
      to?: string | null,
      seqNum?: BigNumberish | null,
      data?: null
    ): TypedEventFilter<
      [string, string, BigNumber, string],
      { from: string; to: string; seqNum: BigNumber; data: string }
    >;
  };

  estimateGas: {
    inbox(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    inbox(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
