/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Signer,
  utils,
  BigNumberish,
  Contract,
  ContractFactory,
  Overrides,
} from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Poll, PollInterface } from "../Poll";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        internalType: "uint256",
        name: "_choiceID",
        type: "uint256",
      },
    ],
    name: "vote",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "endBlock",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [],
    name: "destroy",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_endBlock",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "voter",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "choiceID",
        type: "uint256",
      },
    ],
    name: "Vote",
    type: "event",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516101d23803806101d28339818101604052602081101561003357600080fd5b505160005561018b806100476000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80630121b93f14610046578063083c63231461006557806383197ef01461007f575b600080fd5b6100636004803603602081101561005c57600080fd5b5035610087565b005b61006d610106565b60408051918252519081900360200190f35b61006361010c565b6000544311156100cd576040805162461bcd60e51b815260206004820152600c60248201526b3837b6361034b99037bb32b960a11b604482015290519081900360640190fd5b60408051828152905133917ff668ead05c744b9178e571d2edb452e72baf6529c8d72160e64e59b50d865bd0919081900360200190a250565b60005481565b6000544311610153576040805162461bcd60e51b815260206004820152600e60248201526d706f6c6c2069732061637469766560901b604482015290519081900360640190fd5b33fffea265627a7a72315820030d4ccd58e03ab2b59cf24b943e793300efd59c00f7528ae973ab9bcfda1de664736f6c634300050b0032";

export class Poll__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    _endBlock: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Poll> {
    return super.deploy(_endBlock, overrides || {}) as Promise<Poll>;
  }
  getDeployTransaction(
    _endBlock: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_endBlock, overrides || {});
  }
  attach(address: string): Poll {
    return super.attach(address) as Poll;
  }
  connect(signer: Signer): Poll__factory {
    return super.connect(signer) as Poll__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PollInterface {
    return new utils.Interface(_abi) as PollInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Poll {
    return new Contract(address, _abi, signerOrProvider) as Poll;
  }
}
