/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import {BytesLike} from "@ethersproject/bytes";
import {Listener, Provider} from "@ethersproject/providers";
import {FunctionFragment, EventFragment, Result} from "@ethersproject/abi";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface FeeDistributorV1Interface extends ethers.utils.Interface {
  functions: {
    "a()": FunctionFragment;
    "changePayees(address[],uint256[])": FunctionFragment;
    "getPayees()": FunctionFragment;
    "lastReleasedAt()": FunctionFragment;
    "payees(uint256)": FunctionFragment;
    "release()": FunctionFragment;
    "shares(address)": FunctionFragment;
    "totalShares()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "a", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "changePayees",
    values: [string[], BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "getPayees", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lastReleasedAt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "payees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "release", values?: undefined): string;
  encodeFunctionData(functionFragment: "shares", values: [string]): string;
  encodeFunctionData(
    functionFragment: "totalShares",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "a", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changePayees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPayees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastReleasedAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payees", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "shares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalShares",
    data: BytesLike
  ): Result;

  events: {
    "FeeReleased(uint256,uint256)": EventFragment;
    "PayeeAdded(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "FeeReleased"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PayeeAdded"): EventFragment;
}

export type FeeReleasedEvent = TypedEvent<
  [BigNumber, BigNumber],
  {income: BigNumber; releasedAt: BigNumber}
>;

export type FeeReleasedEventFilter = TypedEventFilter<FeeReleasedEvent>;

export type PayeeAddedEvent = TypedEvent<
  [string, BigNumber],
  {account: string; shares: BigNumber}
>;

export type PayeeAddedEventFilter = TypedEventFilter<PayeeAddedEvent>;

export interface FeeDistributorV1 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FeeDistributorV1Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    a(overrides?: CallOverrides): Promise<[string]>;

    changePayees(
      _payees: string[],
      _shares: BigNumberish[],
      overrides?: Overrides & {from?: string | Promise<string>}
    ): Promise<ContractTransaction>;

    getPayees(overrides?: CallOverrides): Promise<[string[]]>;

    lastReleasedAt(overrides?: CallOverrides): Promise<[BigNumber]>;

    payees(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    release(
      overrides?: Overrides & {from?: string | Promise<string>}
    ): Promise<ContractTransaction>;

    shares(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    totalShares(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  a(overrides?: CallOverrides): Promise<string>;

  changePayees(
    _payees: string[],
    _shares: BigNumberish[],
    overrides?: Overrides & {from?: string | Promise<string>}
  ): Promise<ContractTransaction>;

  getPayees(overrides?: CallOverrides): Promise<string[]>;

  lastReleasedAt(overrides?: CallOverrides): Promise<BigNumber>;

  payees(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  release(
    overrides?: Overrides & {from?: string | Promise<string>}
  ): Promise<ContractTransaction>;

  shares(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  totalShares(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    a(overrides?: CallOverrides): Promise<string>;

    changePayees(
      _payees: string[],
      _shares: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    getPayees(overrides?: CallOverrides): Promise<string[]>;

    lastReleasedAt(overrides?: CallOverrides): Promise<BigNumber>;

    payees(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    release(overrides?: CallOverrides): Promise<void>;

    shares(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    totalShares(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "FeeReleased(uint256,uint256)"(
      income?: null,
      releasedAt?: null
    ): FeeReleasedEventFilter;
    FeeReleased(income?: null, releasedAt?: null): FeeReleasedEventFilter;

    "PayeeAdded(address,uint256)"(
      account?: null,
      shares?: null
    ): PayeeAddedEventFilter;
    PayeeAdded(account?: null, shares?: null): PayeeAddedEventFilter;
  };

  estimateGas: {
    a(overrides?: CallOverrides): Promise<BigNumber>;

    changePayees(
      _payees: string[],
      _shares: BigNumberish[],
      overrides?: Overrides & {from?: string | Promise<string>}
    ): Promise<BigNumber>;

    getPayees(overrides?: CallOverrides): Promise<BigNumber>;

    lastReleasedAt(overrides?: CallOverrides): Promise<BigNumber>;

    payees(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    release(
      overrides?: Overrides & {from?: string | Promise<string>}
    ): Promise<BigNumber>;

    shares(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    totalShares(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    a(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    changePayees(
      _payees: string[],
      _shares: BigNumberish[],
      overrides?: Overrides & {from?: string | Promise<string>}
    ): Promise<PopulatedTransaction>;

    getPayees(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastReleasedAt(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    payees(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    release(
      overrides?: Overrides & {from?: string | Promise<string>}
    ): Promise<PopulatedTransaction>;

    shares(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalShares(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
