/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface TestSortedDoublyLLFindWithHints2Interface
  extends ethers.utils.Interface {
  functions: {
    "test_insert_findWithHintNextRemoved()": FunctionFragment;
    "test_insert_findWithHintNextIncreased()": FunctionFragment;
    "test_insert_findWithHintPrevRemovedUpdateHead()": FunctionFragment;
    "beforeEach()": FunctionFragment;
    "test_insert_findWithHintPrevDecreased()": FunctionFragment;
    "test_insert_findWithHintNextRemovedUpdateTail()": FunctionFragment;
    "test_insert_findWithHintPrevRemoved()": FunctionFragment;
    "test_insert_findWithHintNotTightBound()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "test_insert_findWithHintNextRemoved",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test_insert_findWithHintNextIncreased",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test_insert_findWithHintPrevRemovedUpdateHead",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "beforeEach",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test_insert_findWithHintPrevDecreased",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test_insert_findWithHintNextRemovedUpdateTail",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test_insert_findWithHintPrevRemoved",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test_insert_findWithHintNotTightBound",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "test_insert_findWithHintNextRemoved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_insert_findWithHintNextIncreased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_insert_findWithHintPrevRemovedUpdateHead",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "beforeEach", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "test_insert_findWithHintPrevDecreased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_insert_findWithHintNextRemovedUpdateTail",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_insert_findWithHintPrevRemoved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_insert_findWithHintNotTightBound",
    data: BytesLike
  ): Result;

  events: {};
}

export class TestSortedDoublyLLFindWithHints2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TestSortedDoublyLLFindWithHints2Interface;

  functions: {
    test_insert_findWithHintNextRemoved(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    test_insert_findWithHintNextIncreased(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    test_insert_findWithHintPrevRemovedUpdateHead(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    beforeEach(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    test_insert_findWithHintPrevDecreased(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    test_insert_findWithHintNextRemovedUpdateTail(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    test_insert_findWithHintPrevRemoved(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    test_insert_findWithHintNotTightBound(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  test_insert_findWithHintNextRemoved(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  test_insert_findWithHintNextIncreased(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  test_insert_findWithHintPrevRemovedUpdateHead(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  beforeEach(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  test_insert_findWithHintPrevDecreased(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  test_insert_findWithHintNextRemovedUpdateTail(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  test_insert_findWithHintPrevRemoved(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  test_insert_findWithHintNotTightBound(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    test_insert_findWithHintNextRemoved(
      overrides?: CallOverrides
    ): Promise<void>;

    test_insert_findWithHintNextIncreased(
      overrides?: CallOverrides
    ): Promise<void>;

    test_insert_findWithHintPrevRemovedUpdateHead(
      overrides?: CallOverrides
    ): Promise<void>;

    beforeEach(overrides?: CallOverrides): Promise<void>;

    test_insert_findWithHintPrevDecreased(
      overrides?: CallOverrides
    ): Promise<void>;

    test_insert_findWithHintNextRemovedUpdateTail(
      overrides?: CallOverrides
    ): Promise<void>;

    test_insert_findWithHintPrevRemoved(
      overrides?: CallOverrides
    ): Promise<void>;

    test_insert_findWithHintNotTightBound(
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    test_insert_findWithHintNextRemoved(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    test_insert_findWithHintNextIncreased(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    test_insert_findWithHintPrevRemovedUpdateHead(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    beforeEach(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    test_insert_findWithHintPrevDecreased(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    test_insert_findWithHintNextRemovedUpdateTail(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    test_insert_findWithHintPrevRemoved(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    test_insert_findWithHintNotTightBound(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    test_insert_findWithHintNextRemoved(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    test_insert_findWithHintNextIncreased(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    test_insert_findWithHintPrevRemovedUpdateHead(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    beforeEach(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    test_insert_findWithHintPrevDecreased(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    test_insert_findWithHintNextRemovedUpdateTail(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    test_insert_findWithHintPrevRemoved(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    test_insert_findWithHintNotTightBound(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
